title = "Zola Bear+ Theme"
base_url = "https://salcc.github.io/zola-bearplus"
description = "Minimalistic yet a bit featureful theme for Zola, based on Bear Blog"

compile_sass = false
build_search_index = false

taxonomies = [
  {name = "categories", feed = true},
  {name = "tags", feed = true},
]

[markdown]
highlight_code = true
highlight_theme = "css"
highlight_themes_css = [
  { theme = "OneHalfDark", filename = "syntax-theme-dark.css" },
  { theme = "OneHalfLight", filename = "syntax-theme-light.css" },
]

[extra]
date_format="%d %b, %Y"
mathjax = true

[[extra.main_menu]]
name = "Blog"
url = "@/blog/_index.md"

[[extra.main_menu]]
name = "GitHub"
url = "https://github.com/salcc/zola-bearplus"
