name = "Bear+"
description = "Minimalistic yet a bit featureful theme for Zola, based on Bear Blog"
license = "MIT"
homepage = "https://salcc.github.io/zola-bearplus"

min_version = "0.4.0"
demo = "https://salcc.github.io/zola-bearplus"

# Any variable there can be overridden in the end user `config.toml`
# You don't need to prefix variables by the theme name but as this will
# be merged with user data, some kind of prefix or nesting is preferable
# Use snake_casing to be consistent with the rest of Zola
[extra]

[author]
name = "Marçal Comajoan Cara"
homepage = "https://salcc.github.io"

[original]
author = "Alan Pearce"
homepage = "https://alanpearce.eu"
repo = "https://codeberg.org/alanpearce/zola-bearblog"
