name = "Bear+"
description = "Minimalistic yet a bit featureful theme for the Zola static site generator."
license = "MIT"
homepage = "https://marçal.cc/zola-bearplus"

min_version = "0.17.2"
demo = "https://marçal.cc/zola-bearplus"

[author]
name = "Marçal Comajoan Cara"
homepage = "https://marçal.cc"

[original]
author = "Alan Pearce"
homepage = "https://alanpearce.eu"
repo = "https://codeberg.org/alanpearce/zola-bearblog"
